### ISSUE TITLE
pcap conversion fails

### ISSUE THREAD

**Issue by aidenmitchell** [mtagius/pwnagotchi-tools#2]
```
    default: Processing: STEENBUCK007
    default: Main catch: Error: Command failed: hcxpcaptool -z ../pmkid/STEENBUCK007_0220da4207d5.pmkid /handshakes/pcap/STEENBUCK007_0220da4207d5.pcap
    default: /bin/sh: 1: hcxpcaptool: not found
    default: Error: Command failed: hcxpcaptool -o ../hccapx/STEENBUCK007_0220da4207d5.hccapx /handshakes/pcap/STEENBUCK007_0220da4207d5.pcap
    default: /bin/sh: 1: hcxpcaptool: not found
    default:
    default:     at ChildProcess.exithandler (child_process.js:303:12)
    default:     at ChildProcess.emit (events.js:315:20)
    default:     at maybeClose (internal/child_process.js:1021:16)
    default:     at Socket.<anonymous> (internal/child_process.js:443:11)
    default:     at Socket.emit (events.js:315:20)
    default:     at Pipe.<anonymous> (net.js:675:12) {
    default:   killed: false,
    default:   code: 127,
    default:   signal: null,
    default:   cmd: 'hcxpcaptool -o ../hccapx/STEENBUCK007_0220da4207d5.hccapx /handshakes/pcap/STEENBUCK007_0220da4207d5.pcap'
    default: }
```

**Comment by mtagius** [comment]
Can you give me any context? Did you run the Vagrant VM or run the script manually?

**Comment by aidenmitchell** [comment]
I ran ```vagrant up```.

**Comment by mtagius** [comment]
hmm, try `vagrant destroy -f` and then `vagrant up` again. This time take a look at the vagrant output and post everything after `git clone https://github.com/ZerBea/hcxtools.git` runs from the vagrant script.

**Comment by mtagius** [comment]
I pushed a fix that worked for me. Pull the update and see if it works for you. Thank you for bringing this to my attention!

**Comment by aidenmitchell** [comment]
That fixed it, thanks!
